#! configuration/base.yaml

application:
  port: 8000

database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password" # used locally only. When deploying to DigitalOcean, a strong password is used
  database_name: "newsletter"

email_client:
  base_url: "localhost"
  sender_email: "test@gmail.com"
  authorization_token: "873fa009-f43b-4494-a791-0d39c68792f4"
  timeout_milliseconds: 10000